name: Second workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu:latest
    steps:
      - name: doublerun
        run: |
          echo "first run"
          echo "second run"
    
